### ISSUE TITLE
Unable to run Sara 

### ISSUE THREAD

**Issue by Codesam1** [termuxhackers-id/SARA#2]
~/SARA $ python3 sara.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/SARA/sara.py", line 231, in <module>
    check_requirements()
  File "/data/data/com.termux/files/home/SARA/sara.py", line 25, in check_requirements
    java_version=os.popen("java --version","r").read().splitlines()[0]
IndexError: list index out of range

 I tried to rerun it but it brought this out

**Comment by KakaoXI** [comment]
Same

**Comment by termuxhackers-id** [comment]
Fixed
