### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by h4x0rl33t** [termuxhackers-id/SARA#24]
I: Smaling smali folder into classes.dex...
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
        at org.jf.dexlib2.writer.DexWriter.writeAnnotationDirectories(DexWriter.java:790)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:340)
        at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
        at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
        at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
        at brut.androlib.Androlib.buildSources(Androlib.java:350)
        at brut.androlib.Androlib.build(Androlib.java:302)
        at brut.androlib.Androlib.build(Androlib.java:269)
        at brut.apktool.Main.cmdBuild(Main.java:238)
        at brut.apktool.Main.main(Main.java:76)
[!] Failed to signed APK's

**Comment by termuxhackers-id** [comment]
Make sure the apktool version is 2.4.0 or 2.4.0-1
